[package]
authors = ["Sam Grimee <sgrimee@gmail.com>"]
categories = ["command-line-utilities"]
description = "A minimalist terminal user interface for Cisco Webex Teams"
documentation = "https://github.com/sgrimee/webex-tui"
edition = "2021"
homepage = "https://github.com/sgrimee/webex-tui"
keywords = ["cisco", "webex", "tui", "cli", "terminal"]
license = "MIT OR Apache-2.0"
name = "webex-tui"
repository = "https://github.com/sgrimee/webex-tui"
version = "0.5.0"

[dependencies]
chrono = { version = "0.4.31" }
clap = { version = "4.3.19", features = ["cargo"] }
color-eyre = "0.6.2"
crossterm = "0.27"
dirs = "5.0.1"
enum-iterator = "1.4.1"
gethostname = "0.4.3"
html2text = { version = "0.7.0", features = ["ansi_colours"] }
itertools = "0.12.0"
log = "0.4.19"
# markdown = "0.3.0"
# mini_markdown = "0.3.5"
oauth2 = "4.4.1"
open = "5.0.0"
ratatui = "0.24.0"
serde = { version = "1.0.180", features = ["derive"] }
serde_yaml = "0.9.25"
textwrap = "0.16.0"
tokio = { version = "1.29.1", features = ["rt", "macros"] }
tui-logger = "0.10.0"
tui-textarea = "0.4.0"
webbrowser = "0.8.11"
# webex = "0.9.1"
# webex = { path = "../vendor/webex-rust" }
webex = { git = "https://github.com/sgrimee/webex-rust.git", rev = "23bc8ebe40a411c597f9ccee512fa5b22a4c7887" }
# webex = { git = "https://github.com/sgrimee/webex-rust.git", branch = "42-api_alignment_sgrimee" }

[dev-dependencies]
rstest = "0.18.2"
