[package]
name = "webex-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
disk-persist = "0.1.0"
eyre = "0.6.8"
log = "0.4.19"
oauth2 = "4.4.1"
open = "5.0.0"
tokio = { version = "1.29.1", features = ["rt", "macros"] }
tui = { version = "0.19.0", features = ["crossterm"] }
tui-logger = "0.9.2"
webex = { version = "0.7.0", path = "../webex-rust" }
