[package]
name = "webex-tui"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/sgrimee/webex-tui"
documentation = "https://github.com/sgrimee/webex-tui"
repository = "https://github.com/sgrimee/webex-tui"
keywords = ["cisco", "webex", "tui", "cli", "terminal"]
categories = ["command-line-utilities"]
authors = ["Sam Grimee <sgrimee@gmail.com>"]
license = "MIT OR Apache-2.0"


[dependencies]
chrono = { version = "0.4.31" }
clap = "4.3.19"
color-eyre = "0.6.2"
crossterm = "0.27"
dirs = "5.0.1"
enum-iterator = "1.4.1"
log = "0.4.19"
oauth2 = "4.4.1"
open = "5.0.0"
ratatui = "0.23.0"
ratatui-textarea = { version = "0.3.2", features = ["ratatui"] }
serde = { version = "1.0.180", features = ["derive"] }
serde_yaml = "0.9.25"
tokio = { version = "1.29.1", features = ["rt", "macros"] }
tui-logger = { version = "0.9.5", default-features = false, features = [
    "ratatui-support",
] }
# webex = "0.8.0"
webex = { version = "0.8.0", git = "https://github.com/sgrimee/webex-rust.git" }
# webex = { path = "../vendor/webex-rust" }
