[package]
name = "webex-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
eyre = "0.6.8"
log = "0.4.19"
oauth2 = "4.4.1"
open = "5.0.0"
ratatui = "0.22.0"
tokio = { version = "1.29.1", features = ["rt", "macros"] }
tui-logger = { git = "https://github.com/gin66/tui-logger.git", default-features = false, features = [
    "ratatui-support",
] } # until https://github.com/gin66/tui-logger/issues/41
tui-textarea = { git = "https://github.com/sgrimee/tui-textarea.git", features = [
    "ratatui-crossterm",
], default-features = false } # until https://github.com/rhysd/tui-textarea/issues/18

# webex = { version = "0.7.0", git = "https://github.com/sgrimee/webex-rust.git" }
webex = { path = "../webex-rust" }
