# Example user configuration for webex-tui
# Place this file at ~/.config/webex-tui/config.yml

# Theme to use (default: "default")
theme: "dracula"

# Number of messages to load per room (default: 10)  
messages_to_load: 20

# Enable debug logging (default: false)
debug: false