name: "Default"

# Clean, functional theme with good contrast for most terminals
# Uses standard terminal colors with semantic role assignments

palette:
  black: "black"
  red: "red"
  green: "green"
  yellow: "yellow"
  blue: "blue"
  magenta: "magenta"
  cyan: "cyan"
  white: "white"
  bright_black: "gray"
  bright_red: "light_red"
  bright_green: "light_green"
  bright_yellow: "light_yellow"
  bright_blue: "light_blue"
  bright_magenta: "light_magenta"
  bright_cyan: "light_cyan"
  bright_white: "white"

roles:
  background: "reset"
  text_primary: "reset"
  text_muted: "gray"
  accent: "light_cyan"
  selection_bg: "blue"
  selection_fg: "white"
  border: "gray"
  border_active: "cyan"
  title: "light_cyan"
  hint: "gray"
  room_unread: "light_blue"
  room_team: "light_cyan"
  msg_timestamp: "gray"
  log_error: "red"
  log_warn: "yellow"
  log_info: "blue"
  log_debug: "green"
  log_trace: "gray"
  compose_status: "yellow"

user_colors:
  - "light_blue"
  - "light_green"
  - "light_yellow"
  - "light_magenta"
  - "light_cyan"
  - "blue"
  - "green"
  - "yellow"
  - "magenta"
  - "cyan"
